# Generated by Django 4.0.4 on 2022-05-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50)),
                ('level', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=50)),
                ('department', models.CharField(choices=[('General', 'General'), ('Computer Science', 'Computer Science'), ('Information System', 'Information System'), ('Information Technology', 'Information Technology'), ('Decision Support', 'Decision Support'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
