# Generated by Django 4.0.4 on 2022-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photo/back.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
