# Generated by Django 4.0.4 on 2022-05-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos\x12\x05\x019.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
